/** ui */
const ui = {
  SET_FROSTED_GLASS: 'SET_FROSTED_GLASS',
  SET_LOADING: 'SET_LOADING',
};

/** temp */
const bike = {
  SET_BIKE_STATIONS: 'SET_BIKE_STATIONS',
  SET_BIKE_STATIONS_AVAILABILITY: 'SET_BIKE_STATIONS_AVAILABILITY',
};

export {
  ui, bike,
};
